### ISSUE TITLE
Execução no Windows 10

### ISSUE THREAD

**Issue by ProZorD** [abntex/limarka#116]
**Comportamento esperado**:

Geração do PDF

**Passos para reprodução**:

limarka exec

**Especificações do sistema**:

C:/Ruby23/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboard/windows.rb:15:in `rescue in <module:Windows>': Could not load the required ffi gem, install it with: gem install ffi (LoadError)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboard/windows.rb:12:in `<module:Windows>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboard/windows.rb:4:in `<module:Clipboard>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboard/windows.rb:3:in `<top (required)>'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboard.rb:32:in `const_get'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboard.rb:32:in `implementation'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboard.rb:55:in `<top (required)>'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/limarka-0.6.1/lib/limarka/ref.rb:5:in `<top (required)>'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/limarka-0.6.1/lib/limarka/cli.rb:9:in `<top (required)>'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/limarka-0.6.1/lib/limarka.rb:2:in `<top (required)>'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/limarka-0.6.1/exe/limarka:7:in `<top (required)>'
        from C:/Ruby23/bin/limarka:22:in `load'
        from C:/Ruby23/bin/limarka:22:in `<main>'

**Comment by edusantana** [comment]
Realizado em #115
