### ISSUE TITLE
Referências dentro do texto em numeração aletatória ao invés de crescente

### ISSUE THREAD

**Issue by andresimi** [abntex/limarka#123]
**Comportamento esperado**:
Que as referências dentro do texto estejam em ordem crescente

**Passos para reprodução**:
Colocar umas 4 citações no texto. Depois citá-las ao mesmo tempo em ordem aleatória. Ele obedece a ordem aleatória ao invés de colocá-las em ordem crescente.

![image](https://cloud.githubusercontent.com/assets/7464255/22177897/554c9b40-e00f-11e6-9ef1-55097af78ffb.png)

**Especificações do sistema**:
Ubuntu1604 - gedit

**Comment by edusantana** [comment]
Apenas para esclarecer, as referências são listadas de acordo com a ordem do texto. Se esse trecho tivesse sido utilizado na primeira página do texto (sem nenhuma outra citação sendo realizada), eles estaria ordenados como desejado pelo autor do issue.

Infelizmente o abnTeX não oferece esta funcionalidade. Não irei implementá-la porque o esforço não compensa. Caso realmente deseja-se ordenar as referências ela pode ser realizada manualmente.

Outro detalhe, talvez algumas pessoas não desejem ordená-las, pois podem preferir utilizar as referências mais importantes primeiro, o que seria perdido caso fosse ordenado.

Obrigado pela contribuição, mas infelizmente essa funcionalidade não será implementada.
