### ISSUE TITLE
Erro ao ler campos multi-linhas de configuração salva com o PDF-XChange Viewer 

### ISSUE THREAD

**Issue by andresimi** [abntex/limarka#124]
**Comportamento esperado**:
Que o gerador de abreviaturas as gere.

**Passos para reprodução**:
Colocar 2 siglas no pdf de configuração, só a primeira é gerada. A de OMS não foi gerada.
![image](https://cloud.githubusercontent.com/assets/7464255/22177912/c7a9c2e4-e00f-11e6-9563-d54cab4e8362.png)

**Especificações do sistema**:
Ubuntu 1604 - PDF X Viewer

**Comment by edusantana** [comment]
O problema é o Leitor de PDF, que está codificando a quebra de linha com outro caractere.

Utilizando pdftk para ler os campos de `configuracao.pdf` salvos pelo **Evince** (leitor padrão no Ubuntu):
```
---
FieldType: Text
FieldName: siglas
FieldNameAlt: Sigla: Descricao da sigla
FieldFlags: 4096
FieldValue: DSM-V: Manual Diagnósico e Estatístico de Transtornos Mentais, 5a edição
OMS: Organização Mundial de Saúde
FieldValueDefault: ABNT: Associação Brasileira de Normas Técnicas
FieldJustification: Center
```

Utilizando pdftk para ler os campos de `configuracao.pdf` salvos pelo **PDF XCHANGE VIEWER**:

```
FieldType: Text
FieldName: siglas
FieldNameAlt: Sigla: Descricao da sigla
FieldFlags: 4096
FieldValue: DSM-V: Manual Diagnósico e Estatístico de Transtornos Mentais, 5a edição^MOMS: Organização Mundial de Saúde
FieldValueDefault: ABNT: Associação Brasileira de Normas Técnicas
FieldJustification: Center
```

As possíveis soluções seriam:

1. Tentar fazer o editor utilizar quebra de linha. Talvez modificar a codificação do ambiente de execução do wine.
2. Cadastrar bug em [pdf-forms](https://github.com/jkraemer/pdf-forms) e aguardar solução. E tentar implementar solução.
3. Tenta outra solução no limarka.

**Work around**:

Por enquanto utilizar o evince:

![siglas](https://cloud.githubusercontent.com/assets/3603111/22178825/27d29d4c-e021-11e6-88ae-ec7c7cbb065a.png)

**Comment by edusantana** [comment]
Eu acho que dá para o limarka converter o `\r` em `\n` e depois fazer o parse. Tenho que investigar melhor a implementação disso.

```
$ irb
irb(main):001:0> require 'pdf_forms'
=> true
irb(main):003:0> pdftk = PdfForms.new('pdftk')
=> #<PdfForms::PdftkWrapper:0x000000012a7208 @pdftk="/usr/bin/pdftk", @options={}>
irb(main):006:0>  pdf = PdfForms::Pdf.new 'configuracao.pdf', pdftk, utf8_fields: true
=> #<PdfForms::Pdf:0x00000000e9ca50 @options={:utf8_fields=>true}, @path="configuracao.pdf", @pdftk=#<PdfForms::PdftkWrapper:0x000000012a7208 @pdftk="/usr/bin/pdftk", @options={}>>
irb(main):007:0> pdf.field "siglas"
=> #<PdfForms::Field:0x00000001393540 @type="Text", @name="siglas", @name_alt="Sigla: Descricao da sigla", @flags="4096", @value="DSM-V: Manual Diagnósico e Estatístico de Transtornos Mentais, 5a edição\rOMS: Organização Mundial de Saúde", @value_default="ABNT: Associação Brasileira de Normas Técnicas", @justification="Center">
```

Arquivo utilizado: [configuracao.pdf](https://github.com/abntex/limarka/files/721667/configuracao.pdf)
