### ISSUE TITLE
Exibir mensagem indicando a versão requerida do pandoc após instalação

### ISSUE THREAD

**Issue by AllanDaemon** [abntex/limarka#138]
Após atualização do gem do Limarka com o comando especificado pela wiki:

`sudo gem install limarka`

Ao tentar compilar (`limarka`) um arquivo que antes estava funcionando, ele gera um erro.

**Especificações do sistema**:
Linux 64bits
Bunsen Labs distro, baseado no Debian Unstable (SID)
```
$ limarka --version
limarka 0.7.1
```

**Saida do Erro**

```
$ limarka
Erro: /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `[]': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `filtra_json'
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/exe/pandoc_abnt:9:in `<top (required)>'
	from /usr/local/bin/pandoc_abnt:22:in `load'
	from /usr/local/bin/pandoc_abnt:22:in `<main>'
pandoc: Error running filter pandoc_abnt
Filter returned error status 1

Erro: /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `[]': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `filtra_json'
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/exe/pandoc_abnt:9:in `<top (required)>'
	from /usr/local/bin/pandoc_abnt:22:in `load'
	from /usr/local/bin/pandoc_abnt:22:in `<main>'
pandoc: Error running filter pandoc_abnt
Filter returned error status 1

Erro: /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `[]': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `filtra_json'
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/exe/pandoc_abnt:9:in `<top (required)>'
	from /usr/local/bin/pandoc_abnt:22:in `load'
	from /usr/local/bin/pandoc_abnt:22:in `<main>'
pandoc: Error running filter pandoc_abnt
Filter returned error status 1

Erro: /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `[]': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `filtra_json'
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/exe/pandoc_abnt:9:in `<top (required)>'
	from /usr/local/bin/pandoc_abnt:22:in `load'
	from /usr/local/bin/pandoc_abnt:22:in `<main>'
pandoc: Error running filter pandoc_abnt
Filter returned error status 1

Erro: /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `[]': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `filtra_json'
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/exe/pandoc_abnt:9:in `<top (required)>'
	from /usr/local/bin/pandoc_abnt:22:in `load'
	from /usr/local/bin/pandoc_abnt:22:in `<main>'
pandoc: Error running filter pandoc_abnt
Filter returned error status 1

Erro: /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `[]': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `filtra_json'
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/exe/pandoc_abnt:9:in `<top (required)>'
	from /usr/local/bin/pandoc_abnt:22:in `load'
	from /usr/local/bin/pandoc_abnt:22:in `<main>'
pandoc: Error running filter pandoc_abnt
Filter returned error status 1

Erro: /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `[]': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `filtra_json'
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/exe/pandoc_abnt:9:in `<top (required)>'
	from /usr/local/bin/pandoc_abnt:22:in `load'
	from /usr/local/bin/pandoc_abnt:22:in `<main>'
pandoc: Error running filter pandoc_abnt
Filter returned error status 1

Erro: /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `[]': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `filtra_json'
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/exe/pandoc_abnt:9:in `<top (required)>'
	from /usr/local/bin/pandoc_abnt:22:in `load'
	from /usr/local/bin/pandoc_abnt:22:in `<main>'
pandoc: Error running filter pandoc_abnt
Filter returned error status 1

Erro: /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `[]': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `filtra_json'
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/exe/pandoc_abnt:9:in `<top (required)>'
	from /usr/local/bin/pandoc_abnt:22:in `load'
	from /usr/local/bin/pandoc_abnt:22:in `<main>'
pandoc: Error running filter pandoc_abnt
Filter returned error status 1

Erro: /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `[]': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `filtra_json'
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/exe/pandoc_abnt:9:in `<top (required)>'
	from /usr/local/bin/pandoc_abnt:22:in `load'
	from /usr/local/bin/pandoc_abnt:22:in `<main>'
pandoc: Error running filter pandoc_abnt
Filter returned error status 1

Erro: /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `[]': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `filtra_json'
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/exe/pandoc_abnt:9:in `<top (required)>'
	from /usr/local/bin/pandoc_abnt:22:in `load'
	from /usr/local/bin/pandoc_abnt:22:in `<main>'
pandoc: Error running filter pandoc_abnt
Filter returned error status 1

Erro: /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `[]': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `filtra_json'
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/exe/pandoc_abnt:9:in `<top (required)>'
	from /usr/local/bin/pandoc_abnt:22:in `load'
	from /usr/local/bin/pandoc_abnt:22:in `<main>'
pandoc: Error running filter pandoc_abnt
Filter returned error status 1

Erro: /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `[]': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/lib/pandoc_abnt/figura_filter.rb:84:in `filtra_json'
	from /var/lib/gems/2.3.0/gems/pandoc_abnt-1.0.4/exe/pandoc_abnt:9:in `<top (required)>'
	from /usr/local/bin/pandoc_abnt:22:in `load'
	from /usr/local/bin/pandoc_abnt:22:in `<main>'
pandoc: Error running filter pandoc_abnt
Filter returned error status 1

Erro: pandoc: unrecognized option `--top-level-division=chapter'
Try pandoc --help for more information.

Erro: pandoc: unrecognized option `--top-level-division=chapter'
Try pandoc --help for more information.

Erro: pandoc: unrecognized option `--top-level-division=chapter'
Try pandoc --help for more information.

Erro: pandoc: unrecognized option `--top-level-division=chapter'
Try pandoc --help for more information.
```

**Comment by AllanDaemon** [comment]
Instalando a versão `0.6.7` especificamente funciona ok.

A as versões `0.7.0` e `0.6.7` dão o mesmo erro.

**Comment by edusantana** [comment]
> OBS: Recomenda-se instalar a última versão do pandoc manualmente. A partir da versão v0.7.1 o limarka requer pandoc >= v1.19.1. - [Instalação no Linux](https://github.com/abntex/limarka/wiki/Instala%C3%A7%C3%A3o-no-Linux#depend%C3%AAncias)

Qual sua versão do pandoc?

**Comment by edusantana** [comment]
Como imprimir mensagem após instalação:
- http://brandonhilkert.com/blog/ruby-gem-post-install-message/
- https://github.com/jnunemaker/httparty/blob/v0.13.7/httparty.gemspec#L22

**Comment by AllanDaemon** [comment]
Meu computador queimou. Mas como uso Debian Unstable, deveria ser a ultima versão do pandoc instalada. 

De acordo com https://packages.debian.org/sid/pandoc, a versão utilizada é a `1.17.2~dfsg-3`.

Se voce usa alguma distribuição baseada em Debian, como Ubuntu, o Pandoc terá esa versão ou mais antiga.

**Comment by edusantana** [comment]
Você pode verificar a última versão do pandoc em https://github.com/jgm/pandoc/releases/latest

Eu entendo o que você está falando:

> ao requer a versão `1.19.1` não será possível executar o limarka em distribuições sem atualizar o pandoc manualmente, não é isso?

Infelizmente foi uma decisão que tive que tomar. Pois o limarka também funciona no Windows. E houve uma mudança significativa no modo de trabalhar do pandoc a partir dessa versão (1.9.1). Os usuários do windows iriam baixar a versão nova para instalar... então o limarka precisaria ser compatível com a versão mais nova do pandoc.

Como o projeto é novo, e daqui a pouco as novas distribuições virão com o pandoc mais novo, preferi quebrar a compatibilidade do que manter dois códigos distintos para processar a mesma tarefa de modo diferentes.

Você precisará [baixar e instalar a versão mais nova manualmente](https://github.com/abntex/limarka/wiki/Instala%C3%A7%C3%A3o-no-Linux). Baixa o arquivo deb novo e executa `sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb`

**Comment by edusantana** [comment]
@AllanDaemon é possível configurar o travis para gerar o PDF automaticamente para você. Para isso seria necessário:

- manter o repositório de seu TCC no github (público)
- criar o arquivo de configuração [travis baseado no do limarka](https://github.com/abntex/limarka/blob/master/.travis.yml)
- configurar a geração e o deployment do arquivo PDF gerado através de releases do github

Isto possibilitaria você trabalhar em seu TCC de qualquer lugar, editando através do editor do Github on-line, ou utilizar o git para editar localmente.

Você teria os seguintes inconvenientes:

- Manter o TCC em repositório público
- Demorar aproximadamente 17 min para geração de Cada PDF

**Comment by AllanDaemon** [comment]
Esse bug também acontece com a ultima versão do Ubuntu LTS, 16.04.

```
$ limarka --version
limarka 0.7.1
```

```
$ pandoc --version
pandoc 1.16.0.2
```

**Comment by AllanDaemon** [comment]
Entendo a quesão do suporte ao windows. Mas a questão é que no Linux, em especial nas plataformas Debian que são boa parte das distros, ela ainda não chegou. Isso quer dizer que em algumas plataformas como as estaveis, ele ficara muito tempo até chgar esa versão.

Isso quer dizer que pra maioria das plataformas linux, o limarka ficaria com mais de 4 anos sem suporte, exeto por alguns hacks mais complicados, que podem gerar incompatibiliade com o resto o sistema.

**Comment by edusantana** [comment]
> o limarka ficaria com mais de 4 anos sem suporte, exeto por alguns hacks mais complicados

Oi @AllanDaemon, não é um hack. É apenas instalar a versão mais nova de um aplicativo. Não é necessário compilar nada, basta baixar o arquivo `.deb` e instalar. Esse é o processo normal de instalação de vários aplicativos que não estão no repositório do apt-get.

> que podem gerar incompatibiliade com o resto o sistema.

**Você não terá problemas de compatibilidade porque o pandoc não é uma biblioteca, é um aplicativo**.

As instruções para instalação são:

    wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
    sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb

É normal necessitar instalar as versões mais novas de determinados aplicativos que estamos utilizando, eu sempre verifico os Releases Notes para verificar se as novas funcionalidades e correções trazem melhorias significativas que afetam o meu trabalho. Se a nova versão trás melhorias ou correções que afetam o meu trabalho, não preciso ficar aguardado o repositório do debian ser atualizado.
