### ISSUE TITLE
Identação na lista de siglas

### ISSUE THREAD

**Issue by andresimi** [abntex/limarka#139]
**Comportamento esperado**:
Que mantivesse a identação na lista de siglas.
![teste ](https://files.gitter.im/abntex/limarka/VbFx/blob)

**Passos para reprodução**:
Gerar uma sigla de 9 caracteres

**Especificações do sistema**:
Ubuntu 1604 PDF Xchange

**Comment by edusantana** [comment]
@andresimi eu vou defender minha dissertação na próxima semana, estou fazendo os slides. Você tem urgência nisso, ou pode esperar um pouco mais?
Eu procurei nos fóruns e não achei ninguém relatando o mesmo problema. Daí vou ter que investigar um pouco mais, talvez até olhar o código fonte para compreender o problema.

**Comment by andresimi** [comment]
Eu estou entregando minha tese hoje, consigo arrumar isso num editor de pdf. Dá pra esperar.

**Comment by edusantana** [comment]
Reproduzindo o erro:

```tex
\begin{siglas}
  \item[ABNT] Associação Brasileira de Normas Técnicas
  \item[SUPRE-MISS] Será que o espaçamento está bom?
  \item[abnTeX] ABsurdas Normas para TeX
\end{siglas}
% ---
```

![lista-de-abreviaturas](https://cloud.githubusercontent.com/assets/3603111/24732160/6d9a2b7a-1a45-11e7-9ff7-581d128c0394.png)

**Comment by edusantana** [comment]
**Workaround**: Utilizar o comando `\hspace{}` adicionar espaço nas entradas menores:

```tex
\begin{siglas}
  \item[ABNT] \hspace{0.50cm} Associação Brasileira de Normas Técnicas
  \item[SUPRE-MISS] Será que o espaçamento está bom?
  \item[abnTeX] \hspace{0.50cm} ABsurdas Normas para TeX
\end{siglas}
```

![siglas-workaround](https://cloud.githubusercontent.com/assets/3603111/24732563/fcc76900-1a47-11e7-8b38-0f6fc3195110.png)

http://www.maths.tcd.ie/~dwilkins/LaTeXPrimer/WhiteSpace.html

**Comment by edusantana** [comment]
Simulando alterações no limarka. Atualize a lista de siglas com o seguinte conteúdo:

```
ABNT: \hspace{0.50cm} Associação Brasileira de Normas Técnicas
SUPRE-MISS: Será que o espaçamento está bom?
abnTeX: \hspace{0.50cm} ABsurdas Normas para TeX
```

![siglas-limarka-com-espaco-horizontal](https://cloud.githubusercontent.com/assets/3603111/24732851/1de00e1a-1a4a-11e7-94fe-307ae8edee3e.png)

**Comment by edusantana** [comment]
@andresimi Eu vou fechar esse issue, pois com estas instruções é possível corrigir o problema.

**Comment by andresimi** [comment]
Oi @edusantana, obrigado. Só pra dizer que tive pra obter a solução completa precisei também do \hspace* que adiciona espaços que persistem após quebra de linha. Visto que, como mostra a primeira figura, uma parte da palavra *Behaviors* não ficava identada. Então ficou assim:

RS: \hspace{0.50cm} Rio Grande do Sul
SUPRE-MISS: *Suicide Prevention Multisite Intervention Study on Suicidal Beha- \hspace*{0.5cm} viors*
UFRGS: \hspace{0.50cm} Universidade Federal do Rio Grande do Sul

**Comment by renanwp2** [comment]
Tive vários problemas. Um deles foi: 

> You can't use `macro parameter character #' in horizontal mode. {\normalfont{#

**Comment by renanwp2** [comment]
Em vez de fazer manualmente, eu pensei no seguinte. Imagine que sua maior sigla seja:

> UNICAMP - FCA 

No caso, sempre que for definir uma SIGLA, faça:

> \parbox{\widthof{UNICAMP - FCA}}{SIGLA} 

Assim, fica da seguinte maneira o uso do comando siglas:

> \begin{siglas}
  \item[\parbox{\widthof{UNICAMP - FCA}}{ABNT}]  Associação Brasileira de Normas Técnicas
  \item[\parbox{\widthof{UNICAMP - FCA}}{SUPRE-MISS}] Será que o espaçamento está bom?
  \item[\parbox{\widthof{UNICAMP - FCA}}{abnTeX}] ABsurdas Normas para TeX
  \item[\parbox{\widthof{UNICAMP - FCA}}{UNICAMP - FCA}] University of Campinas School of Applied Sciences 
\end{siglas}

`\widthof` é um comando do pacote `calc`. Então basta adicionar o pacote: 

> \usepackage{calc}

Em geral, a maior sigla dá para se determinar no olho. Então assim, fica bom. Apesar de chato, assim fica do tamanho exato.
