### ISSUE TITLE
Retirar a numeração do sumário da introdução/apresentação.

### ISSUE THREAD

**Issue by yzakius** [abntex/limarka#142]
**Comportamento esperado**:

Que a contagem seja feita a partir do "Capítulo" e não da "Introdução".  Exemplo: ao invés de termos "1 Introdução", "2 Capítulo...", termos: "Introdução", "1 Capítulo".

**Comment by edusantana** [comment]
# Capítulos ou seções não numeradas

Para criar um capítulo não numerado utilize `{-}` após o título do capítulo:

```
# Introdução {-}

Texto da introdução, capítulo não numerado.

# Primeiro capítulo

Texto do primeiro capítulo aqui.
```

![introducao-nao-numerada](https://cloud.githubusercontent.com/assets/3603111/24776671/3717cf72-1af8-11e7-9a74-dbde04561bf4.png)

**Comment by edusantana** [comment]
@yzakius verifica se assim fica bom para você. Eu atualizei a [documentação do wiki](https://github.com/abntex/limarka/wiki/Como-criar-elementos#cap%C3%ADtulos-ou-se%C3%A7%C3%B5es-n%C3%A3o-numeradas) mostrando como fazer isso.

**Comment by yzakius** [comment]
Opa @edusantana funcionando perfeitamente. Obrigado!
