### ISSUE TITLE
Possibilitar invocar filtros pandoc

### ISSUE THREAD

**Issue by lfpdroubi** [abntex/limarka#158]
**Comportamento esperado**:
Seria desejável que o limarka permitisse a utilização de filtros do pandoc, como o pandoc-eqnos (https://github.com/tomduck/pandoc-eqnos), para inserção automática de numeração e referência cruzada de equações com o markdown.

**Passos para reprodução**:
Atualmente, é necessário introduzir as equações em código latex para obter a mesma funcionalidade.

**Especificações do sistema**:

**Comment by edusantana** [comment]
Eu posso gerar uma versão beta para você testar. 
Qual o sistema que você utiliza?
Quais as configurações que pretende utilizar com esse filtro?

**Comment by lfpdroubi** [comment]
Bom dia @edusantana! Eu utilizo o Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-97-generic x86_64) no google cloud.

Eu nunca utilizei o filtro em questão. Pesquisando como numerar automaticamente as equações com o Markdown, encontrei este link: https://tex.stackexchange.com/questions/158798/number-equations-in-pandoc-by-default

No repositório do pandoc-eqnos (https://github.com/tomduck/pandoc-eqnos), a seção *usage* recomenda:

To apply the filter during document processing, use the following option with pandoc:

--filter pandoc-eqnos
Note that any use of --filter pandoc-citeproc or --bibliography=FILE options should come after the pandoc-eqnos filter call.

**Comment by edusantana** [comment]
Oi @lfpdroubi eu marquei como uma melhoria a ser implementada, mas com prioridade baixa. Aumentarei a prioridade se você ou outra pessoa estiver realmente necessitando dela.

**Comment by edusantana** [comment]
Filtros para testar:
- https://github.com/chdemko/pandoc-latex-admonition
- [https://github.com/jgm/pandoc/wiki/Pandoc-Filters](https://github.com/jgm/pandoc/wiki/Pandoc-Filters)

**Comment by edusantana** [comment]
A partir da versão 19.7 é possível invocar filtros, [wiki](https://github.com/abntex/limarka/wiki/Configura%C3%A7%C3%B5es-avan%C3%A7adas#filtros-pandoc)
