### ISSUE TITLE
Tornar o limarka compatível com o pandoc 2.0

### ISSUE THREAD

**Issue by edusantana** [abntex/limarka#159]
**Comportamento esperado**:

Uma nova versão major do pandoc foi lançada hoje. Atualizar o limarka para tornar compatível.

**Comment by cauachagas** [comment]
Atualizei meu sistema na partição Linux. Está assim agora 

pandoc 2.0.6
ruby 2.5.0p0 (2017-12-25 revision 61468)
XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017/Arch Linux)
Latexmk, John Collins, 19 Jan. 2017. Version 4.52c

O Limarka apresenta erro com o [--normalize](https://github.com/abntex/limarka/blob/master/lib/limarka/conversor.rb#L177), que agora diz ser feito automaticamente. Então o retirei. 

Usei os arquivos do repositório [dissertacao-limarka](https://github.com/edusantana/dissertacao-limarka) e o modelo padrão do limarka para testes.

Pelo o que puder perceber, só a entrada de imagens com o formato Markdown que está com problemas. Está gerando imagens assim 
![issue159](https://user-images.githubusercontent.com/26585248/34702497-c94cd1c2-f4cc-11e7-8f9f-44e22618b770.png) 

usando {#passaro width=40%}, que está na modelo padrão

Uma solução é em colocar também o parâmetro heigth . 

Ex: 
{#passaro height=40% width=40%} 
![image](https://user-images.githubusercontent.com/26585248/34704734-f1cc1f38-f4d9-11e7-9d2e-e9a622ded328.png)

Mas deixa a foto com especto quadrado (1:1), enquanto que imagem original tem um aspecto por volta de 6:4. Eu esperava que fosse escalonar, mantendo o mesmo aspecto, por conta do "%".  

Outra opção  é usar height e width com os valores da altura e largura sem o "%"



A entrada feita com o comando figura, que gera código latex, está normal.

**Comment by edusantana** [comment]
Esse momento eventualmente iria chegar... atualizar para pandoc 2.x, eu estava postergando rs. 

Entra em contato comigo através do [gitter](gitter.im/abntex/limarka). Eu vou atualizar conforme as funcionalidades você estiver necessitando.

**Comment by cauachagas** [comment]
@edusantana .Hoje eu estava tentando usar o pandoc para gerar um pdf com as normas da ABNT sem o uso do limarka. Usando um monte de filtros, incluido o pandoc_abnt, acabei reparando que não gerava esse erro no aspecto da imagem. Procurando alguma coisa relacionado ao pacote "graphicx", encontrei os seguintes comandos 

```latex
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
```
Colando no preambulo do modelo padrão do limarka,  resolveu o problema das imagens (estou no pandoc 2.2).

Tanto "escala=xx%", quanto "width=xx%" está funcionando.

**Comment by edusantana** [comment]
Para torna-se compatível com a versão 2.0 o limarka precisou apenas remover a opção de utilização do normalize, o trabalho maior foi na atualização do filtro de imagens do pandoc_abnt.
