### ISSUE TITLE
Correção no wiki sobre dependências de compilação no Ubuntu 17.10.1

### ISSUE THREAD

**Issue by serdasteclas** [abntex/limarka#160]
Seguindo os passos da wiki tive um erro ao compilar o Limarka em uma instalação limpa do ultimo Ubuntu.
Para conseguir instalar no Ubuntu 17.10.1 precisei instalar algumas libs que não estão no comando da wiki, o seguinte comando resolveu o problema de compilação: 
`apt-get install libffi6 libffi-dev jabref`

**Comment by edusantana** [comment]
Estranho. Eu desconheço as duas primeiras dependências, mas a última é o jabref (que é desnecessário para compilação). De toda forma, atualizei o wiki, obrigado!
