### ISSUE TITLE
Atualizar instruções e compatibilidade para utilização do tinytex

### ISSUE THREAD

**Issue by edusantana** [abntex/limarka#164]
O [tinytex](https://yihui.name/tinytex/) é uma versão compactada do Latex, seria interessante verificar a compatibilidade, uma vez que diminui as dependências.

Quem souber das instruções e testes pode adicionar aqui.

**Comment by cauachagas** [comment]
Há duas maneiras de instalar o TinyTex: via script (terminal) ou pela linguagem R. 

Aqui descrevo os passos para instalar numa máquina com Windows 7 via terminal. Caso sua máquina tenha Windows 8 em diante, ignore o passo 1.


1 - Para instalar o TinyTex no Windows 7 é preciso instalar primeiramente o [Power Shell](https://download.microsoft.com/download/E/7/6/E76850B8-DA6E-4FF5-8CCE-A24FC513FD16/Windows6.1-KB2506143-x64.msu). Desde o Windows 8, o Power Shell já vem instalado.

2 - Salvar o [script](https://raw.githubusercontent.com/yihui/tinytex/master/tools/install-windows.bat) num bloco de notas com nome *install-windows.bat* (Pelo menos com navegador Chrome no Windows 7, Ctrl + S salva com extensão .txt e não como .bat, por isso usei o bloco de notas).

3 - Depois é dar um duplo click em *install-windows.bat* para ele fazer o download do TinyTex e sua instalação.

Se aparecer um erro falando de luatex é normal. Segundo a documentação, é só apertar OK. ![](https://db.yihui.name/images/install-tl-win-lua.png)

O script instala o TinyTex em "C:\Users\NOME DO USUARIO\AppData\Roaming\TinyTeX\bin\win32"

**OBS**:  Testei num outro computador que o nome do usuário tinha espaço e acentos e não funciona (coisa de Ruimdows). Neste caso, será necessário mudar o script para que instale numa outra pasta (Por exemplo, em "C:\"), mas isso eu não descreverei aqui. 

4 - Depois de Instalado o TinyTex é necessário colocá-lo no path (não sei fazer isso via terminal no windows. Uma ajuda aí, @edusantana ). 

5 - Para rodar o template do Limarka é preciso instalar alguns pacotes. Eles são:

- abntex2
- memoir
- ifetex
- textcase
- enumitem
- lastpage
- microtype
- lipsum
- xcolor
- pdfpages
- babel-portuges

Abra o powershell ou cmd digite
```bash
tlmgr install abntex2 memoir ifetex textcase enumitem lastpage microtype lipsum xcolor pdfpages babel-portuges
```

para instalar os pacotes.

**Comment by cauachagas** [comment]
Para os usuários que utilizam R creio que é só fazer 
```R
install.packages('tinytex') # instala o pacote no R 
library(tinytex) #  chama o pacote
tinytex::install_tinytex() # instala o TinyTex na máquina
tlmgr_install('nome do pacote')  # comando para instalar os pacotes LaTeX 
``` 

Acho que depois é só colocar a pasta no path para o TinyTex poder ser usado fora do R. O TinyTex fica instalado em "C:\Users\NOME DO USUÁRIO\Documents\R\win-library\3.5\tinytex\bin" ou algo do tipo.

**Comment by edusantana** [comment]
Obrigado @cauachagas 
Você está utilizando TinyTex?
A possibilidade de utilização do limarka sem precisar instalar o Latex gigantão é maravilhosa. 

Quer me ajudar na adaptação do limarka para possibilitar isso?

**Comment by edusantana** [comment]
Criei uma [branch para testar o TinyTex](https://travis-ci.org/abntex/limarka/branches).

**Comment by cauachagas** [comment]
Não estou utilizando, por ora. Só aprovetei que tem computadores com Ruimdows no laboratório sem LaTeX instalado. Mas basta dizer como posso ajudar que eu posso tentar. 
Sinceramente, não tenho conhecimento de GitHub, se não eu teria mandado algumas sugestões para soluções.

**Comment by edusantana** [comment]
@cauachagas agora o limarka está utilizando o tinytex. Obrigado!
