### ISSUE TITLE
Pacote pdftk no Ubuntu 18.04

### ISSUE THREAD

**Issue by dsoaress** [abntex/limarka#168]
O pacote pdftk foi removido do repositório oficial. Tem um fork:
`sudo add-apt-repository ppa:malteworld/ppa`
`sudo apt update`

E então prosseguir com a instalação das dependências como informado na wiki:
`sudo apt-get install ruby-full pandoc pdftk poppler-utils xclip latexmk texlive-full make gcc`

**Comment by dsoaress** [comment]
Segue uma sugestão para a wiki de instalação.

[Instalação-no-Linux.md](https://github.com/abntex/limarka/files/2729520/Instalacao-no-Linux.md.zip)

**Comment by dsoaress** [comment]
@edusantana combinado. Alterei a página mas a primeira linha com o comando ficou quebrada em duas linhas, talvez confunda usuários pouco experientes. Contudo preferi deixar toda a observação como um parágrafo inteiro para não causar a impressão que é um passo a mais para todos.

**Comment by cauachagas** [comment]
Eu estou voltando a usar o Linux Mint. Pra contornar isso, baixei o pdftk do Ubuntu 18.10, que agora é [pdftk-java](https://packages.ubuntu.com/cosmic/all/pdftk-java/download). Serve como outra alternativa. 

Para quem usar Ubuntu 18.10 e posteriores ou Debian buster/Sid é a maneira correta de instalação, até o momento.
