### ISSUE TITLE
Melhorar os quadros

### ISSUE THREAD

**Issue by edusantana** [abntex/limarka#183]
Incluir no modelo e no docker:

```tex
\usepackage{boldline}
\def\toprule{\hlineB{3}}
\def\midrule{\hline}
\def\bottomrule{\hlineB{3}}
```

**Comment by cauachagas** [comment]
Para usar *boldline* se faz necessário adicionar o pacote *shipunov*. Adicionando

```latex
tlmgr install shipunov
``` 
no pacotes basicos do tinytex resolve o problema.

**Comment by cauachagas** [comment]
Fechado com os commits abntex/limarka@472ed7d e [ fa9328c](https://github.com/abntex/trabalho-academico-limarka/commit/fa9328cc277289a87cd1708ae182da5524b7a061)
