### ISSUE TITLE
Remote repository is newer than local (2018 < 2019)

### ISSUE THREAD

**Issue by maraal** [abntex/limarka#186]
**Comportamento esperado**:
Que a imagem fosse construída sem probemas depois de rodar o comando:

`docker build -t limarka:customizada - < limarka/Dockerfile`

**Passos para reprodução**:

```
docker pull limarka/limarka  
wget https://github.com/abntex/trabalho-academico-limarka/raw/master/Dockerfile
mv Dockerfile limarka
docker build -t limarka:customizada - < limarka/Dockerfile 
```
``` 
tlmgr: Remote repository is newer than local (2018 < 2019)
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
Please see https://tug.org/texlive/upgrade.html for details.
```

**Especificações do sistema**:

```
docker version

Docker version 18.09.5-ce, build e8ff056dbc

docker run limarka/limarka --version

limarka 1.0.2
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.1.2, skylighting 0.7.4
Default user data directory: /root/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]

pdftk 2.02 a Handy Tool for Manipulating PDF Documents
Copyright (c) 2003-13 Steward and Lee, LLC - Please Visit: www.pdftk.com
This is free software; see the source code for copying conditions. There is
NO warranty, not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Latexmk, John Collins, 25 October 2018. Version 4.61
XeTeX 3.14159265-2.6-0.99999 (TeX Live 2018)
kpathsea version 6.3.0
Copyright 2018 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 61.1; using 61.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.9.0; using 2.9.0
Compiled with Graphite2 version 1.3.11; using 1.3.11
Compiled with HarfBuzz version 1.7.6; using 1.7.6
Compiled with libpng version 1.6.34; using 1.6.34
Compiled with poppler version 0.63.0
Compiled with fontconfig version 2.11.0; using 2.11.0


```

**Comment by edusantana** [comment]
Olá @maraal 
Obrigado por sua contribuição!

Estou com um pouco de dificuldades de gerar a próxima versão devido a #181 

Ainda [não entendi bem](https://travis-ci.org/abntex/limarka/builds/534040828) qual o problema que estamos tendo na execução dos testes.

Assim que finalizar isso, posso gerar uma nova versão da imagem docker. Atualmente eu automatizei o processo de geração das imagens docker, para ser geradas no servidor. Mas para isso os testes devem está passando...

Vou tentar fazer isso esse final de semana. Obrigado por reportar o problema!

Acho que teremos isso daí todo ano, uma vez que o repositório do texlive é atualizado anualmente.

**Comment by maraal** [comment]
Pelo que eu pude perceber, normalmente poderiamos colocar para um dos repositórios antigos mas parece que eles "congelaram" todos os repositórios antigos. Percebi isso quando adicionei a seguinte linha ao `DOCKERFILE`
```
RUN tlmgr option repository http://mirror.ctan.org/systems/texlive/tlnet
RUN tlmgr update --self

```

**Comment by edusantana** [comment]
@maraal existe esse workaround, eu fiz algo semelhante em minha máquina...

Mas não lembrava qual era o código. Mas de toda forma, o que está precisando é gerar novamente a imagem, com a versão nova. Infelizmente não conseguir gerar, pq no meu computador os testes estão passando... mas no servidor estão falhando, precisa de mais investigação.

**Comment by rt3norio** [comment]
como é o workaround pra que funcione? não utilizar a imagem personalizada?

**Comment by edusantana** [comment]
@rt3norio acredito que seria adicionar no [Docekfile, nesse local](https://github.com/abntex/trabalho-academico-limarka/blob/master/Dockerfile#L5), o seguinte conteúdo:

```
RUN tlmgr option repository http://mirror.ctan.org/systems/texlive/tlnet
RUN tlmgr update --self
```

Depois [seguir as instruções para gerar a imagem customizada](https://github.com/abntex/limarka/wiki/Limarka-com-Docker#gerando-uma-imagem-customizada).

**Comment by edusantana** [comment]
@rt3norio você pode utilizar [a imagem de desenvolvimento](https://github.com/abntex/limarka/wiki/Limarka-com-Docker#vers%C3%A3o-de-desenvolvimento-1) na imagem customizada.

**Comment by edusantana** [comment]
Corrigido com a publicação da última versão.
