### ISSUE TITLE
Não é possível gerar um .pdf via travis usando o trabalho-academico-limarka

### ISSUE THREAD

**Issue by sergiopvilar** [abntex/limarka#198]
Aparentemente o `tlmgr` precisa ser atualizado na imagem `ruby-latex-pandoc`. Atualmente é impossível concluir o deploy no travis pois a mensagem de atualização retorna um código de erro.

```
tlmgr itself needs to be updated.
Please do this via either
  tlmgr update --self
or by getting the latest updater for Unix-ish systems:
  http://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.sh
and/or Windows systems:
  http://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.exe
Then continue with other updates as usual.
===============================================================================
tlmgr: Terminating; please see warning above!
tlmgr: package repository http://mirrors.concertpass.com/tex-archive/systems/texlive/tlnet (verified)
The command '/bin/sh -c tlmgr install subfig' returned a non-zero code: 255```

**Comment by edusantana** [comment]
Oi @sergiovilar

Não utilizamos mais essa imagem. Verifique as instruções em https://github.com/abntex/limarka/wiki/Limarka-com-Docker

Nós temos duas imagens. Uma com a versão oficial e outra para versão em desenvolvimento.

Teste com a nova imagem, e avisa se persistir o problema, ok?

**Comment by sergiovilar** [comment]
Ok, vou fazer o teste. Seria necessário então atualizar a documentação em https://github.com/abntex/limarka/wiki/Experimentar-sem-instalar?

Muito obrigado.

**Comment by edusantana** [comment]
@sergiovilar vi que [seu build passou](https://travis-ci.org/sergiovilar/trabalho-academico-limarka/builds/562148945).

Ainda está tendo algum problema?

**Comment by sergiopvilar** [comment]
Deu tudo certo, estou fechando!
