### ISSUE TITLE
Atualizar a documentação em refêrencia ao pacote build-essential, em distros baseadas no Debian, para a instalação da gem limarka.

### ISSUE THREAD

**Issue by stickway** [abntex/limarka#199]
Linux Mint apresenta o erro `ERROR: Failed to build gem native extension` na instalação da gem. O problema é resolvido ao instalar o pacote `build-essential` no repositório.

Sugestão de mudança:

[limarka-wiki.zip](https://github.com/abntex/limarka/files/3623984/limarka-wiki.zip)

**Comment by edusantana** [comment]
@stickway você poderia realizar a edição?

https://github.com/abntex/limarka/wiki/Instalação-no-Linux

Se não tiver permissão me avisa.

**Comment by stickway** [comment]
@edusantana acho que ainda estou sem permissão

**Comment by edusantana** [comment]
![Captura de tela de 2019-09-20 17-26-58](https://user-images.githubusercontent.com/3603111/65356876-e8144f80-dbcb-11e9-9656-637e97792327.png)

Ok, enviei o convite agora, poderia tentar novamente?
Acho que precisa aceitar o convite antes.

**Comment by stickway** [comment]
Realizei as seguintes alterações:

![alteração 1](https://user-images.githubusercontent.com/54927022/65357892-94efcc00-dbce-11e9-94e0-4706d245b685.jpg)


Adicionei o pacote na seção dependências 


![alteração 2](https://user-images.githubusercontent.com/54927022/65357933-b51f8b00-dbce-11e9-8c2d-e957c6bb6642.jpg)


Faltava um l no comando `latexmk --version`

**Comment by edusantana** [comment]
Perfeito! Obrigado!
