### ISSUE TITLE
Dúvida: alguma forma de não imprimir folha de rosto? Múltiplos autores?

### ISSUE THREAD

**Issue by sergiopvilar** [abntex/limarka#200]
Olá,

Tenho usado o Limarka para trabalhos acadêmicos que não exigem Folha de Rosto mas que demandam que o trabalho seja feito por mais de um autor, como por exemplo, um relatório de um experimento.

Seria possível que uma das duas opções fossem implementadas?
- Permitir que um mesmo trabalho tenha múltiplos autores
- Folha de rosto seja escondida

Caso sim me disponibilizo pra estudar o código e fazer um PR.

Desde já muito obrigado.

**Comment by edusantana** [comment]
É só modificar o template, o código LaTeX dentro da pasta template. Estou sem o PC, depois mostro exatamente aonde.

**Comment by edusantana** [comment]
https://github.com/abntex/trabalho-academico-limarka/blob/85e68399b53886586567fd4555349bac744e08b3/templates/pretextual1-folha_de_rosto.latex#L6

**Comment by cauachagas** [comment]
@sergiopvilar , sobre mulitplos autores... Acho que a opção mais viável é criar um novo comando (`\renewcommand{\imprimircapa}`) baseado neste [trecho](https://github.com/abntex/abntex2/blob/09d4f592cf41422a2bd882a8422887b2efd74912/tex/latex/abntex2/abntex2.cls#L1038-L1055) e colocar em [latexcustomizacao.sty](https://github.com/abntex/trabalho-academico-limarka/blob/master/latexcustomizacao.sty#L9). Como é algo pré-pronto, fiz um exemplo abaixo.

```latex
% ---
% Impressão da Capa
\renewcommand{\imprimircapa}{%
  \begin{capa}%
    \center
    \ABNTEXchapterfont\large\imprimirautor \\ % nome do autor no formulário
    \ABNTEXchapterfont\large{Nome do Autor 2} \\
    \ABNTEXchapterfont\large{Nome do Autor 3} \\

    \vfill
    \begin{center}
    \ABNTEXchapterfont\bfseries\LARGE\imprimirtitulo
    \end{center}
    \vfill
    
    \large\imprimirlocal

    \large\imprimirdata
    
    \vspace*{1cm}
  \end{capa}
}
% ---
```

Sobre a folha de rosto, onde o @edusantana apontou, tu podes colocar o comando `\cleardoublepage` para imprimir uma folha em branco ou então comentar os comandos (%) para fazer nada.

Se possível, crie um repositório com sua própria customização. Assim, ficará mais fácil atender suas necessidades e de outros usuários da sua instituição/programa. Veja os exemplos [senac-poa-ads-tcc](https://github.com/limarka/senac-poa-ads-tcc-limarka) e [usp-pps](https://github.com/limarka/usp-pps-trabalho-academico-limarka)

**Comment by sergiopvilar** [comment]
@cauachagas @edusantana gente, muito obrigado! Só de pular a folha de rosto já resolve meu problema pois posso colocar os múltiplos autores numa capa customizada.

Valeu, ajudou demais!
