### ISSUE TITLE
autonomia comunitária

### ISSUE THREAD

**Issue by ghost** [abntex/limarka#209]

**Comment by cauachagas** [comment]
@lucasnuic , tudo bem? Eu sou um dos contribuidores do projeto. 

Fico feliz pelo seu interesse. Quanto ao limarka, vejo que eu realmente deu uma parada. Um dos motivos é a ABNT, além, é claro, da dedicação dos contribuidores para o projeto. Se você for checar, a classe LaTeX para o projeto é o abntex2 e abntex2cite, que também estão parados. Houveram novas mudanças na ABNT nesse tempo. Acredito que a forma mais próximo das normas atuais seria utilizar o abntex2 junto ao [biblatex-abnt](https://github.com/abntex/biblatex-abnt) para as referências bibiliográficas, mas se você checar as [issues da abntex2](https://github.com/abntex/abntex2/issues) verá que ainda tem alguns problemas dessa combinação .
