### ISSUE TITLE
Renomear o repositório para limarka

### ISSUE THREAD

**Issue by edusantana** [abntex/limarka#23]
O projeto precisa de um nome para ter uma identidade, acho que `limarka` está bom: *Linguagem de Marcação baseada no Markdown e abnTeX2*.

@laurocesar não tenho permissão para renomear o projeto, será que você poderia fazer isso?

**Comment by laurocesar** [comment]
@edusantana , foi vc quem propôs o repositório, mas tem certeza que gostaria que ele tivesse esse nome? Acredito que seja melhor ele manter o nome atual, é que mais esclarecedor, e internamente, na wiki, no README, e até em seus arquivos, conter essa sigla. O que acha?

**Comment by edusantana** [comment]
Prefiro renomear:

- cria um identidade para discutir nos fóruns (`#limarka`)
- internamente o executável e as estrutura de diretórios fica melhor (`limarka` vs `trabalho-academico-pandoc-abntex2`)

As correções internamento eu atualizo sem problemas.

**Comment by laurocesar** [comment]
Feito

**Comment by edusantana** [comment]
Obrigado @laurocesar depois eu gravo um vídeo apresentado o projeto ;)
